######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 30 20:31:21 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bank.h board.h card.h game.h player.h space.h
SOURCES += bank.cpp board.cpp card.cpp game.cpp pal.cpp player.cpp space.cpp
